# Generated by Django 4.2.4 on 2023-08-06 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishing_app', '0003_alter_emaillog_recipient_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillog',
            name='recipient_email',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
